### ISSUE TITLE
the displayed "Est Population" of a county differs depending on whether "Consistent Y-Axis" is checked

### ISSUE THREAD

**Issue by jerryasher** [schnerd/covid-tracker#9]
When I examine `Daily New Cases` `Per 100K People`for Los Angeles, and hover over the graph, I see a pop-up displaying statistics including "Est. Population".  That estimate seems to scale by a factor of 15ish according to the checkbox "Consistent Y-Axis".

![image](https://user-images.githubusercontent.com/666633/94319773-3a572180-ff40-11ea-8bef-f8f97dc63eac.png)

vs

![image](https://user-images.githubusercontent.com/666633/94319784-3fb46c00-ff40-11ea-9933-a20d21a4546b.png)

**Comment by schnerd** [comment]
@jerryasher I'm having trouble replicating this.

Non-consistent Y:
![image](https://user-images.githubusercontent.com/875591/94323917-67a9cc80-ff4c-11ea-98ce-2343ffa08136.png)

Consistent Y:
![image](https://user-images.githubusercontent.com/875591/94323904-5b257400-ff4c-11ea-8c2b-b707b30a3e02.png)

In your first screenshot it looks like you are hovering over Sacramento instead of Los Angeles?

Let me know if I'm missing something.

**Comment by jerryasher** [comment]
Jeez, oops and sorry, I clearly was hovering over Sacramento, my apologies.
